# Meson project options for cage and its subprojects.
# Passed to `meson setup` via --native-file.
# Docs: https://mesonbuild.com/Machine-files.html

[built-in options]
default_library = 'static'
prefer_static   = 'true'
buildtype       = 'release'

[project options]
werror     = 'false'
man-pages  = 'disabled'
input_calibration = 'enabled'

[wlroots:project options]
xwayland      = 'enabled'
examples      = 'false'
auto_features = 'enabled'
backends      = 'auto'
renderers     = 'auto'

[wayland:project options]
documentation  = 'false'
dtd_validation = 'false'

[libdrm:project options]
intel = 'enabled'
amdgpu = 'enabled'
vc4 = 'enabled'
